root: true

parser: 'babel-eslint'

extends:
  - eslint:recommended
  - babel

env:
  node: true

parserOptions:
  ecmaVersion: 7

# List of available rules - ESLint http://eslint.org/docs/rules/
# rules:
